use super::{
    AuditPolicy, CsrfPolicy, DEFAULT_GET_SCOPE, EndpointMethod, EndpointPolicy, PathPattern,
    ReauthPolicy,
};

pub const PUBLIC_ROUTES: &[PathPattern] = &[
    PathPattern::Prefix("/webhook/"),
    PathPattern::Prefix("/beszel/"),
    PathPattern::Prefix("/healthchecks/"),
    PathPattern::Prefix("/uptime-kuma/"),
    PathPattern::Prefix("/wud/"),
    PathPattern::Prefix("/authentik/"),
    PathPattern::Prefix("/shelfmark/"),
    PathPattern::Prefix("/prowlarr/"),
    PathPattern::Prefix("/decypharr/"),
    PathPattern::Prefix("/pve/"),
    PathPattern::Prefix("/healthz"),
    PathPattern::Prefix("/metrics"),
    PathPattern::Prefix("/api/ack/"),
    PathPattern::Prefix("/api/emergency/"),
    PathPattern::Prefix("/emergency/"),
    PathPattern::Prefix("/img/"),
    PathPattern::Prefix("/api/auth/login"),
    PathPattern::Prefix("/api/auth/callback"),
    PathPattern::Exact("/api/auth/backchannel-logout"),
    PathPattern::Exact("/api/auth/methods"),
    PathPattern::Exact("/api/auth/password-policy"),
    PathPattern::Exact("/api/auth/local/login"),
    PathPattern::Exact("/api/auth/magic/request"),
    PathPattern::Prefix("/api/auth/magic/callback/"),
    PathPattern::Prefix("/api/auth/passkey/login"),
    PathPattern::Prefix("/api/auth/step-up"),
    PathPattern::Prefix("/static/"),
    PathPattern::Prefix("/favicon.ico"),
    PathPattern::Exact("/api/auth/logout"),
    PathPattern::Exact("/"),
    PathPattern::Exact("/swagger"),
    PathPattern::Exact("/swagger/"),
    PathPattern::Exact("/api/docs"),
    PathPattern::Exact("/api/docs/"),
    PathPattern::Exact("/api/swagger"),
    PathPattern::Exact("/api/swagger/"),
    PathPattern::Exact("/api/swagger-ui"),
    PathPattern::Exact("/api/swagger-ui/"),
    PathPattern::Exact("/legal"),
    PathPattern::Exact("/legal/"),
    PathPattern::Prefix("/legal/"),
    PathPattern::Exact("/ui"),
    PathPattern::Exact("/ui/"),
    PathPattern::Exact("/ui/index.html"),
    PathPattern::Exact("/ui/status"),
    PathPattern::Exact("/ui/flow"),
    PathPattern::Exact("/ui/inhibitions"),
    PathPattern::Exact("/ui/deliveries"),
    PathPattern::Exact("/ui/emergencies"),
    PathPattern::Exact("/ui/logs"),
    PathPattern::Exact("/ui/audit"),
    PathPattern::Exact("/ui/setup"),
    PathPattern::Exact("/ui/render"),
    PathPattern::Exact("/ui/routing"),
    PathPattern::Exact("/ui/cascade"),
    PathPattern::Exact("/ui/delivery"),
    PathPattern::Exact("/ui/grouping"),
    PathPattern::Exact("/ui/auth"),
    PathPattern::Exact("/ui/preview"),
    PathPattern::Exact("/ui/simulator"),
    PathPattern::Exact("/ui/test"),
    PathPattern::Exact("/ui/privacy"),
    PathPattern::Exact("/ui/accessibility"),
    PathPattern::Exact("/ui/terms"),
    PathPattern::Exact("/ui/cookies"),
    PathPattern::Exact("/ui/legal"),
    PathPattern::Exact("/openapi.yaml"),
    PathPattern::Exact("/api/openapi.yaml"),
];

pub const ENDPOINT_POLICIES: &[EndpointPolicy] = &[
    get("/api/auth/me", "status:read"),
    get("/api/auth/config", "auth:read"),
    get("/api/auth/password-policy", "auth:read"),
    get("/api/auth/tokens", DEFAULT_GET_SCOPE),
    get("/api/auth/passkey/credentials", DEFAULT_GET_SCOPE),
    get("/api/logs", "logs:read"),
    get("/api/audit", "audit:read"),
    get("/api/config/backup", "config:read"),
    get("/api/config/export", "admin:*"),
    get("/api/config/backups", "status:read"),
    get("/api/status", "status:read"),
    get("/api/deliveries", "status:read"),
    get("/api/emergencies", "status:read"),
    EndpointPolicy {
        method: EndpointMethod::Get,
        path: PathPattern::EmergencyDetail,
        scope: "status:read",
        csrf: CsrfPolicy::Required,
        reauth: ReauthPolicy::None,
        audit: AuditPolicy::None,
    },
    get("/api/cascade-config", "status:read"),
    get("/api/emergency-config", "status:read"),
    get("/api/setup-status", "status:read"),
    get("/api/channel-test-matrix", "status:read"),
    get("/inhibitions", DEFAULT_GET_SCOPE),
    get("/api/inhibitions", DEFAULT_GET_SCOPE),
    get("/api/render-config", DEFAULT_GET_SCOPE),
    get("/api/ntfy-topics", DEFAULT_GET_SCOPE),
    get("/api/dedup-config", DEFAULT_GET_SCOPE),
    get("/api/delivery-config", DEFAULT_GET_SCOPE),
    get("/api/channel-config", DEFAULT_GET_SCOPE),
    get("/api/ingest-auth", DEFAULT_GET_SCOPE),
    get("/api/schedules", DEFAULT_GET_SCOPE),
    get("/api/acks", DEFAULT_GET_SCOPE),
    get("/api/inhibition-rules", DEFAULT_GET_SCOPE),
    sensitive_mutation("/api/auth/config", "auth:write", "auth.update"),
    sensitive_mutation("/api/auth/tokens", "auth:write", "auth.token.create"),
    EndpointPolicy {
        method: EndpointMethod::Mutation,
        path: PathPattern::Prefix("/api/auth/tokens/"),
        scope: "auth:write",
        csrf: CsrfPolicy::Required,
        reauth: ReauthPolicy::LocalSudo,
        audit: AuditPolicy::Action("auth.token.revoke"),
    },
    sensitive_mutation(
        "/api/auth/totp/setup/start",
        "auth:write",
        "auth.totp.start",
    ),
    sensitive_mutation(
        "/api/auth/totp/setup/confirm",
        "auth:write",
        "auth.totp.enable",
    ),
    sensitive_mutation("/api/auth/totp/disable", "auth:write", "auth.totp.disable"),
    sensitive_mutation(
        "/api/auth/passkey/register/options",
        "auth:write",
        "auth.passkey.register.start",
    ),
    sensitive_mutation(
        "/api/auth/passkey/register/verify",
        "auth:write",
        "auth.passkey.register.finish",
    ),
    EndpointPolicy {
        method: EndpointMethod::Mutation,
        path: PathPattern::Prefix("/api/auth/passkey/credentials/"),
        scope: "auth:write",
        csrf: CsrfPolicy::Required,
        reauth: ReauthPolicy::LocalSudo,
        audit: AuditPolicy::Action("auth.passkey.delete"),
    },
    audited_exempt_mutation(
        "/api/config/import-preview",
        "config:read",
        "config.import_preview",
    ),
    sensitive_mutation("/api/config/restore", "config:write", "config.restore"),
    sensitive_mutation(
        "/api/channel-config",
        "routing:write",
        "config.channel.update",
    ),
    sensitive_mutation(
        "/api/ntfy-topics",
        "routing:write",
        "config.ntfy_topics.update",
    ),
    sensitive_mutation(
        "/api/ingest-auth",
        "routing:write",
        "config.ingest_auth.update",
    ),
    sensitive_mutation("/api/render-config", "render:write", "config.render.update"),
    exempt_mutation("/api/render-preview", "render:write"),
    sensitive_mutation(
        "/api/cascade-config",
        "cascade:write",
        "config.cascade.update",
    ),
    sensitive_mutation("/api/cascade/toggle", "cascade:write", "cascade.toggle"),
    exempt_mutation("/api/client-log", "admin:read"),
    exempt_mutation("/api/policy-simulate", "status:read"),
    sensitive_mutation(
        "/api/delivery-config",
        "delivery:write",
        "config.delivery.update",
    ),
    sensitive_mutation("/api/dedup-config", "dedup:write", "config.dedup.update"),
    sensitive_mutation(
        "/api/inhibition-rules",
        "inhibitions:write",
        "config.inhibition_rules.update",
    ),
    exempt_mutation("/api/inhibition-rules/test", "inhibitions:write"),
    sensitive_mutation(
        "/api/inhibitions/clear",
        "inhibitions:write",
        "runtime.inhibitions.clear",
    ),
    sensitive_mutation(
        "/api/schedules",
        "inhibitions:write",
        "config.schedules.update",
    ),
    sensitive_mutation("/api/acks/clear", "inhibitions:write", "runtime.acks.clear"),
    EndpointPolicy {
        method: EndpointMethod::Mutation,
        path: PathPattern::EmergencyAction,
        scope: "delivery:write",
        csrf: CsrfPolicy::Required,
        reauth: ReauthPolicy::LocalSudo,
        audit: AuditPolicy::Action("emergency.transition"),
    },
    EndpointPolicy {
        method: EndpointMethod::Mutation,
        path: PathPattern::Prefix("/api/test/"),
        scope: "test:write",
        csrf: CsrfPolicy::Required,
        reauth: ReauthPolicy::None,
        audit: AuditPolicy::None,
    },
];

const fn get(path: &'static str, scope: &'static str) -> EndpointPolicy {
    EndpointPolicy {
        method: EndpointMethod::Get,
        path: PathPattern::Exact(path),
        scope,
        csrf: CsrfPolicy::Required,
        reauth: ReauthPolicy::None,
        audit: AuditPolicy::None,
    }
}

const fn sensitive_mutation(
    path: &'static str,
    scope: &'static str,
    audit_action: &'static str,
) -> EndpointPolicy {
    EndpointPolicy {
        method: EndpointMethod::Mutation,
        path: PathPattern::Exact(path),
        scope,
        csrf: CsrfPolicy::Required,
        reauth: ReauthPolicy::LocalSudo,
        audit: AuditPolicy::Action(audit_action),
    }
}

const fn exempt_mutation(path: &'static str, scope: &'static str) -> EndpointPolicy {
    EndpointPolicy {
        method: EndpointMethod::Mutation,
        path: PathPattern::Exact(path),
        scope,
        csrf: CsrfPolicy::Exempt,
        reauth: ReauthPolicy::None,
        audit: AuditPolicy::None,
    }
}

const fn audited_exempt_mutation(
    path: &'static str,
    scope: &'static str,
    audit_action: &'static str,
) -> EndpointPolicy {
    EndpointPolicy {
        method: EndpointMethod::Mutation,
        path: PathPattern::Exact(path),
        scope,
        csrf: CsrfPolicy::Exempt,
        reauth: ReauthPolicy::None,
        audit: AuditPolicy::Action(audit_action),
    }
}
